JELLY-PJT/jelly

config/settings.py, config/urls.py, config/views.py, groups/admin.py, groups/serializers.py, groups/urls.py, groups/views.py, requirements.txt
- create urls, views, serializers related to group
- install djangorestframework and update requirements.txt
- register Group model to admin
- set index page in config
=> JP-4 #comment [CREATE] urls, views, serializers of group

groups/models.py, groups/serializers.py, groups/urls.py, groups/views.py
=> [ADD] post DRF

.gitignore
- update gitignore file content because of omission
=> [UPDATE] gitignore content

config/settings.py, groups/templates/groups/index.html, groups/urls.py, groups/views.py, requirements.txt, templates/base.html
- create index url, view, template
- delete django-restframwork module in config/settings.py and requirements.txt
=> JP-12 #comment [CREATE] index page and [DELETE] restframework module

groups/forms.py, groups/templates/groups/group_create.html, groups/templates/groups/group_detail.html, groups/templates/groups/index.html, groups/urls.py, groups/views.py
- add group creation button at index.html
- create urls, views, templates, forms for group creation & group detail
=> JP-10 #comment [CREATE] group create & detail function

groups/views.py
add annotation for groups/views.py
=> [ADD] annotation on view function

groups/templates/groups/group_detail.html, static/css/group_detail.css, templates/base.html
group_deatil.html
- 임시로 작성했던 sidebar 삭제
base.html
- axios cdn 추가
- `box-sizing` 속성은 tailwind에 포함되어 있어서 base.css에 따로 추가는 안 했습니다
=> [UPDATE] group_detail.html

config/settings.py, diaries/forms.py, diaries/templates/diaries/create.html, diaries/views.py
ckeditor form required=False로 문제해결
=> JP-5 #comment [UPDATE] diaries-ckeditor 문제해결

config/settings.py, groups/templates/groups/group_detail.html, static/css/group_detail.css
- include sidebar
- 중첩되는 css 속성 변경
=> [UPDATE] group_deatil.html

groups/forms.py, groups/templates/groups/post_detail.html, groups/urls.py, groups/views.py
- create urls, views for post comment and emote function
- add comment, emote content to post detail page
- create comment form
=> JP-17 #comment [CREATE] post comment, emote

diaries/forms.py, diaries/templates/diaries/create.html, diaries/templates/diaries/diary.html, groups/templates/groups/group_detail.html, static/css/base.css, static/css/diary.css, static/css/diary_create.css, static/css/group_detail.css, static/js/diary.js, templates/base.html
- diary.html 작성
- diary_create.html 작성
=> [CREATE] diary.html and diary_create.html

config/settings.py, groups/forms.py, groups/templates/groups/group_detail.html, groups/templates/groups/index.html, groups/views.py, static/css/sidebar.css, templates/sidebar.html, utils/context_processors.py
=> Revert "Feature/modal group create"

groups/forms.py, static/css/sidebar.css, templates/sidebar.html
=> Revert "JP-40 #comment [UPDATE] sidebar scroll, GroupCreate-modal css"

diaries/forms.py, diaries/templates/diaries/diary.html, diaries/templates/diaries/group_detail.html, diaries/views.py, static/css/diary.css, static/js/diary_group.js
- diary.html 작성
- group_detail.html(공유된 다이어리) 작성
- 댓글 좋아요 비동기 처리
=> [CREATE] diary.html and group_detail.html

config/settings.py, groups/forms.py, static/css/sidebar.css, templates/sidebar.html
* settings에 processors추가
* 누락 sidebar, css, groupform 수정
=> [FIX] sidebar

accounts/forms.py, accounts/templates/accounts/profile.html, accounts/urls.py, static/css/flowbite.css, static/css/profile.css, static/css/sidebar.css, static/js/group_detail.js, static/js/profile.js, templates/base.html
- profile.html 작성
- 플로우바이트 css 수정
=> [CREATE] profile.html

groups/templates/groups/group_detail.html, groups/urls.py, groups/views.py, static/js/groups/vote_add_member_option.js, static/js/groups/vote_update.js
- add urls, views, templates, js file for vote update function
- add annotations to js file
=> [CREATE] vote update function incomplete

config/urls.py, schedules/forms.py, schedules/models.py, schedules/urls.py, schedules/views.py
schedules/models.py, urls.py, forms.py, views.py 기본 작성.
마이그레이션은 안했습니다.
=> JP-8 #comment [CREATE] schedules basic

diaries/templates/diaries/group_detail.html, diaries/views.py
- modify group_detail view of diaries
- add total emote count variable to diaries/group_detail.html
=> JP-52 #comment [ADD] total emote count

groups/templates/groups/group_detail.html, static/js/groups/vote_update.js
- 기존에 입력한 value값이 불러와지지 않는 코드 수정 
**고칠 부분**
- 수정하지 않은 투표 선택지는 저장이 되지 않음
=> [FIX] vote update modal

groups/templates/groups/group_detail.html, static/js/groups/vote_update.js
- add name 'options' to input tag of vote options
- delete annotations in vote_update.js
=> JP-47 #comment [FIX] vote update function

static/css/sidebar.css, templates/sidebar.html
* 로고, 개인프로필 사진에 링크 추가
(하핳ㅎㅎ깜박했습니다)
=> [UPDATE] sidebar

groups/templates/groups/group_detail.html, groups/templates/groups/post_detail.html, groups/urls.py, groups/views.py
- create urls, views for notice function
- add notice content in group_detail.html, post_detail.html
=> JP-49 #comment [CREATE] notice function

accounts/templates/accounts/profile.html, diaries/templates/diaries/group_detail.html, diaries/views.py, static/js/diary_group.js
- 공유된 다이어리에 감정 표현, 댓글 수정 비동기 처리
=> JP-60 #comment [UPDATE] emote and comment using Ajax

groups/templates/groups/group_detail.html, static/css/sidebar.css, templates/sidebar.html
- group_detail.html / sidebar.html 호출 시 current_group 맥락 전달
- sidebar.html / 현재 접속 중인 그룹을 구분하는 if 문 추가
- sidebar.css / class 이름 변경 .border-color -> .side-img-border-color
=> [UPDATE] sidebar - 현재 접속 중인 그룹 표시

groups/views.py
- add filter condition when show group notice
=> JP-66 #comment [FIX] group notice

accounts/templates/accounts/profile.html, diaries/templates/diaries/create.html, diaries/templates/diaries/diary.html, diaries/views.py, static/css/diary.css, static/css/diary_create.css, static/css/group_detail.css, static/css/profile.css, static/js/groups/vote_add_member_option.js, static/js/profile.js
=> [UPDATE] css in profile and group_detail

groups/templates/groups/index.html, groups/templates/groups/index/__calendar.html, groups/templates/groups/index/__groups.html, groups/templates/groups/index/__groups_0.html, groups/templates/groups/index/__groups_1.html, groups/templates/groups/index/__search.html, static/css/index.css
- index - 그룹 버튼 스크롤바 추가 / 레이아웃 수정
=> [ADD] index - 그룹 버튼 스크롤바

groups/templates/groups/group_setting.html, static/css/base.css, static/css/group_setting.css, static/css/profile.css
그룹 설정 페이지 작성
- 멤버 관리 부분은 멤버 초대 기능이 구현된 후 수정
=> [CREATE] group_setting.html

accounts/templates/accounts/login.html, accounts/views.py, groups/templates/groups/group_detail.html, groups/templates/groups/group_join.html, groups/templates/groups/group_setting.html, groups/templates/groups/index.html, groups/templates/groups/index/__group_create_modal.html, groups/urls.py, groups/views.py, requirements.txt, static/js/groups/group_invite.js, templates/sidebar.html
- 그룹 초대 페이지 생성
- 그룹 초대했을 때 로그인 후 그룹 초대 페이지로 redirect되도록 login 로직 수정, html에 input tag추가
- 그룹 생성, 그룹 참가, 그룹 암호 수정 등 암호 해싱 관련 함수 작성
- 그룹 디테일 페이지에서 초대링크 클릭 시 url 복사 기능
- 그룹 설정 페이지에 암호 변경 버튼과 모달 추가
- 사이드바 & 인덱스 페이지의 그룹 생성 모달에 password input tag 추가
- argon2 hasher 설치 및 requirements.txt update
- 그룹 탈퇴 기능 추가
=> JP-65 #comment [CREATE] invite & join group, password hashing function

diaries/templates/diaries/group_detail.html
=> [UPDATE] css in diary-group_detail.html

groups/templates/groups/group_setting.html, static/css/group_setting.css
=> [UPDATE] css in group_setting.html

diaries/templates/diaries/create.html, groups/forms.py, groups/templates/groups/post_create.html, static/css/diary_create.css
=> [CREATE] post_create.html

groups/templates/groups/group_detail.html, groups/urls.py, groups/views.py, requirements.txt, static/js/groups/vote_perform.js
- modify groups' url, view, template & create js file for improvement vote perform function
- add allauth to requirements.txt
=> [UPDATE] vote perform function

accounts/templates/accounts/profile.html, diaries/templates/diaries/create.html, diaries/templates/diaries/group_detail.html, diaries/templates/diaries/update.html, diaries/views.py, groups/templates/groups/group_detail.html, static/css/group_detail.css
- group_detail.html에서 공유한 다이어리에도 css 적용
- 다이어리 수정 view함수로 url 연결
- 그룹 나가기 버튼 생성(디자인 추후 수정)
=> [UPDATE] css of shared diary

groups/forms.py, groups/templates/groups/post_detail.html, groups/urls.py, groups/views.py, static/css/diary.css, static/js/post_detail.js, templates/sidebar.html
rebase brain feature/post_detail to main
=> [CREATE] post_detail

groups/templates/groups/group_detail.html, groups/templates/groups/group_join.html, groups/views.py, static/css/group_detail.css, static/css/group_join.css, static/js/groups/group_join.js
- 그룹에 가입하기 위한 암호 입력 페이지 템플릿 작성
=> [CREATE] group_join.html

groups/templates/groups/post_detail.html, static/css/diary.css, static/js/groups/group_detail.js
* 사진 캐루셀로 변경
* 클릭하면 모달로 사진 크게 보기 추가
* static/js 로 넣으면 날라가서 그냥 html파일 안에 js넣었습니다
=> [UPDATE] post_detail_owlcarousel

accounts/models.py, config/settings.py, schedules/models.py, schedules/serializers.py, schedules/tests.py, schedules/views.py
=> [Update] schedule query

accounts/templates/accounts/profile.html, diaries/forms.py, diaries/templates/diaries/create.html, diaries/views.py, static/css/diary.css, static/css/diary_create.css, static/css/profile.css, static/js/diary_create.js, static/js/diary_group.js
profile.html
- 다이어리 썸네일 출력
create.html
- 썸네일을 선택했을 때 해당 사진을 표시하기 위한 css 추가(더 수정할 것)
diary.html
- 작성자 프로필 사진 및 조회수 출력
- 댓글 창으로 바로 이동할 수 있는 버튼 추가
views.py
- 조회수 로직 추가
=> [UPDATE] css of diaires app templates

groups/templates/groups/post_create.html, groups/templates/groups/post_update.html, static/css/diary_create.css
=> [CREATE] post_update.html

diaries/templates/diaries/create.html, diaries/templates/diaries/update.html, diaries/views.py, groups/templates/groups/group_detail.html, groups/templates/groups/group_setting.html, groups/templates/groups/post_create.html, groups/templates/groups/post_detail.html, groups/templates/groups/post_update.html, groups/views.py
- add error messages to view functions of groups & diaries
=> [ADD] error messages

accounts/templates/accounts/login.html, static/css/accounts/login.css, static/css/sidebar.css
* 사이드바 버튼 수정
* 로그인 캐루셀 owl carousel로 변경
=> [UPDATE] login carousel

diaries/templates/diaries/create.html, static/css/diary_create.css, static/js/diary_create.js
- 썸네일용 사진 선택시 뱃지 및 border가 표시되는 css 적용
=> [UPDATE] css of diary create

accounts/views.py, diaries/templates/diaries/group_detail.html, groups/templates/groups/group_detail.html, groups/templates/groups/post_detail.html, groups/views.py, static/css/group_detail.css, static/css/profile.css
=> [UPDATE] all templates

groups/templates/groups/group_detail.html, static/css/vote.css
=> [FIX] vote conflict

chat/consumers.py, chat/templates/chat/room.html, chat/views.py
=> [ADD] chat created_at

chat/templates/chat/room.html, static/css/chat.css
=> [CREATE] chat template

schedules/templates/schedules/group_calendar.html, static/css/group_calendar.css
=> [FIX] calendar selector

groups/templates/groups/group_detail.html, schedules/models.py, schedules/serializers.py, static/css/group_calendar.css, static/js/groups/group_calendar.js, static/js/schedules/Calendar.js, static/js/schedules/Schedule.js
=> [UPDATE] schedule bar display algorithm

diaries/templates/diaries/diary.html, diaries/templates/diaries/group_detail.html, diaries/views.py, static/css/diary.css
=> [UPDATE] shared diary reaction

groups/templates/groups/group_detail.html
=> [FIX] group_detail script

groups/templates/groups/index.html, groups/views.py, schedules/serializers.py, schedules/views.py, static/js/user_calendar.js
[FIX] 프로필 캘린더에서 일정생성시 캘린더 아이디가 들어가지 않는 부분 수정
=> [FIX] profile create schedule

schedules/serializers.py, static/js/user_calendar.js
=> [ADD] schedule filters
